apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumo-backend-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/testlumo/backend:latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: 'https://github.com/testlumo/backend.git'
    targetRevision: HEAD
    path: manifests  # Chemin vers le dossier où se trouvent les manifestes Kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # Namespace où déployer les ressourceseee
  syncPolicy:
    automated:
      prune: true         # Supprime les ressources qui ne sont plus dans les manifestes
      selfHeal: true      # Corrige les écarts détectés automatiquement
