apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumo-backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/testlumo/backend
spec:
  project: default
  source:
    repoURL: 'https://github.com/testlumo/backend.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
