apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumo-backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/testlumo/backend.git'
    targetRevision: main
    path: manifests  # Chemin vers le dossier où se trouvent les manifestes Kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # Namespace où déployer les ressources
  syncPolicy:
    automated:
      prune: true         # Supprime les ressources qui ne sont plus dans les manifestes
      selfHeal: true      # Corrige les écarts détectés automatiquement
    syncOptions:
      - CreateNamespace=true  # Crée le namespace s'il n'existe pas
