apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        kubernetes.io/change-cause: "triggered by GitHub Actions"  # Annotation pour forcer le rollout
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: backend
          image: ghcr.io/testlumo/backend:latest
          imagePullPolicy: Always  # Toujours tirer l'image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: backend
