apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        kubectl.kubernetes.io/restartedAt: "$(date +%Y-%m-%dT%H:%M:%S)"  # Date/heure actuelle
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: backend
          image: ghcr.io/lumosae/backend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: backend
