apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "ghcr.io/testlumo/backend"
    argocd-image-updater.argoproj.io/backend.update-strategy: "latest" # Ajoute cette stratégie pour forcer les updates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest # Utilise le tag 'latest'
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret # Assurez-vous que ce secret est bien configuré
  strategy:
    type: RollingUpdate
