apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: "ghcr.io/testlumo/backend"
    argocd-image-updater.argoproj.io/image-update-strategy: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
  strategy:
    imagePullPolicy: Always
