apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  labels:
    app: lumo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
      annotations:
        keel.sh/update-strategy: "latest"  # Stratégie de mise à jour pour Keel
        keel.sh/image: "ghcr.io/testlumo/backend"  # Image à surveiller pour Keel
        keel.sh/policy: force  # Force la mise à jour de l'image
        keel.sh/trigger: poll  # Déclenche la mise à jour de l'image
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest  # Utilise le tag 'latest'
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret  # Assurez-vous que ce secret est bien configuré
  strategy:
    type: RollingUpdate  # Stratégie de mise à jour
    rollingUpdate:
      maxSurge: 1  # Peut créer un pod supplémentaire
      maxUnavailable: 0  # Pas de pods indisponibles pendant la mise à jour
