apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
      annotations:
        keel.sh/update-strategy: "latest"  # Stratégie de mise à jour
        keel.sh/image: "ghcr.io/testlumo/backend"  # Image à surveiller
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
