apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/testlumo/backend  # Indique à l'updater quel registre surveiller
    argocd-image-updater.argoproj.io/image-update-strategy: tag         # Définit la stratégie de mise à jour sur les tags d'image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest  # Tag à surveiller
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret  # Secret pour accéder au registre d'images
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
