apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/testlumo/backend
    newTag: latest  # ou le tag que vous souhaitez suivre
