apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
