apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  annotations:
    keel.sh/policy: "force"  # Met à jour à chaque fois qu'une nouvelle image est publiée
    keel.sh/trigger: "poll"     # Vérifie périodiquement les nouvelles images
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
