apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumo-backend
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: "poll"
    keel.sh/prune: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumo-backend
  template:
    metadata:
      labels:
        app: lumo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/testlumo/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
