name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_PACKAGE }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [ -n "${{ github.ref_name }}" ]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/testlumo/backend:${{ env.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs only after the build job succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repo to access Kubernetes manifests

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f lumo-backend-deployment.yaml

      - name: Rollout restart
        run: |
          kubectl rollout restart deployment/backend
