name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_PACKAGE }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/testlumo/backend:${{ env.VERSION }}  # Utiliser la version sémantique
            ghcr.io/testlumo/backend:latest               # Tag pour la version la plus récente
            ghcr.io/testlumo/backend:${{ github.sha }}    # Tag basé sur le SHA du commit
